#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/aardvocate/.flutter-sdk/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/aardvocate/src/drawback/frontend/flutter"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/aardvocate/src/drawback/frontend/flutter/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=0.1.0"
export "FLUTTER_BUILD_NUMBER=1"
export "CONFIGURATION_BUILD_DIR=/Users/aardvocate/src/drawback/frontend/flutter/build/ios/iphoneos"
export "DART_DEFINES=QkFDS0VORF9VUkw9aHR0cHM6Ly82YTU3LTE0My0xMDUtMTc0LTIxOC5uZ3Jvay1mcmVlLmFwcC9hcGk=,RkxVVFRFUl9WRVJTSU9OPTMuNDEuMg==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049OTA2NzNhNGVlZg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NmMwYmFhZWJmNw==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMS4w"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/aardvocate/src/drawback/frontend/flutter/.dart_tool/package_config.json"
